# Generated by Django 4.1 on 2022-09-28 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qQuestion_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('qQuestion_User', models.CharField(max_length=100)),
                ('qOriginal_Message', models.TextField(max_length=5000)),
                ('sQuestion_Topic', models.BooleanField(default=False)),
                ('sQuestion_Event', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Summarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_stamp', models.TimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling.question')),
                ('sUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
