# Generated by Django 4.1 on 2022-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_rename_taddiction_1_question_eaddiction_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tskip',
            field=models.BooleanField(default=False),
        ),
    ]
