# Generated by Django 4.1 on 2022-10-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_task_tskip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tskip',
            new_name='tSkip',
        ),
    ]
