# Generated by Django 4.1 on 2022-10-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0006_rename_tskip_task_tskip'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qSkip',
            field=models.BooleanField(default=False),
        ),
    ]
