# Generated by Django 4.1 on 2022-12-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0007_question_qskip'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sQuestion_Filter',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Save'), (1, 'Discuss'), (2, 'Trash')], default=None, null=True),
        ),
    ]
