# Generated by Django 4.1 on 2022-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0008_question_squestion_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sQuestion_Filter',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Save'), (1, 'Discuss'), (2, 'Trash')], default=0, null=True),
        ),
    ]
