# Generated by Django 4.1 on 2022-12-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0010_remove_question_squestion_filter_remove_task_tskip'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sQuestion_Filter',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Save'), (1, 'Discuss'), (2, 'Trash')], default=0, null=True),
        ),
    ]
